### ISSUE TITLE
Model.disableRemoteMethod is deprecated.

### ISSUE THREAD

**Issue by upupzealot** [Neil-UWA/loopback-remote-routing#10]
loopback deprecated Model.disableRemoteMethod is deprecated. 
Use Model.disableRemoteMethodByName instead.
at node_modules/.1.3.2@loopback-remote-routing/remote-routing.js:33:13

In the new version off loopback, disableRemoteMethod method renames to disableRemoteMethodByName.

**Comment by Neil-UWA** [comment]
I suppose you are using loopback@3.X which has breaking changes compared to loopback@2.x. I will look into this problem when I have time.

**Comment by upupzealot** [comment]
Thanks, I made a pull request #11  which works fine for me.
You can test that on your loopback2.x projects.
