### ISSUE TITLE
Missing examples for relations

### ISSUE THREAD

**Issue by xurei** [Neil-UWA/loopback-remote-routing#12]
There should be an example in the docs for configuring the relations.

After digging in the code, I found a way to do it but I'm not sure it's the right way : 
```javascript
RemoteRouting(Model, {only: [
	'@find',
	'@findById',
	'__get__submodel'
]});
```

**Comment by Neil-UWA** [comment]
Actually, there are examples about how to use it directly in the Readme, Its under the section of 

`How to use`

`use directly`

Also, I have already added a link at the bottom of the readme, which tells where you can find the relation names. 
`If you don't know the relation methods name , you can read the doc : http://loopback.io/doc/en/lb3/Exposing-models-over-REST.html`

Anyway, thanks for your feedback, I will make the link more descripsive or add a section on how to get the relation name
