### ISSUE TITLE
deprecated Model.disableRemoteMethod warnings on loopback 3.x

### ISSUE THREAD

**Issue by mrfelton** [Neil-UWA/loopback-remote-routing#15]
It looks like some effort was made to make this module compatible with loopback 3.x, but there is still an issue, specifically here:

https://github.com/Neil-UWA/loopback-remote-routing/blob/246b9e3b308c955003381f3e0e5af7d657a09d5d/remote-routing.js#L31

which results in the following warning when the app boots:

> loopback deprecated Model.disableRemoteMethod is deprecated. Use Model.disableRemoteMethodByName instead. node_modules/loopback-remote-routing/remote-routing.js:31:13

**Comment by Neil-UWA** [comment]
Thx mrfelton, I will take look into it recently.
