### ISSUE TITLE
Problem with routes generated by scopes

### ISSUE THREAD

**Issue by elbrodelche** [Neil-UWA/loopback-remote-routing#17]
These are my model mixins:
~~~
"mixins": {
    "RemoteRouting": {
      "only": [
        "@find",
        "@findOne",
        "@findById",
        "@exists",
        "@count"
      ]
    }
  },
~~~
And i have a scope defined like this:
~~~
"scopes": {
    "top5": {"limit": 5, "order": "business_date"}
  }
~~~

Is there a way for enable GET methos for top5 scope alias??

**Comment by Neil-UWA** [comment]
Yes, you can disable the scope methods.

In ur case, when you define the `top5` scope, loopback will automatically generates a list of related remote methods : 

__get__top5
__create__top5
__delete__top5
__update__top5
__findById__top5
__findOne__top5
__count__top5

These methods are instance methods, which means when you want to disable corresponding methods, you should prefix '@' with the method name, ie. @__get__top5. 

I missed adding the support for findById and _findOne scopes, I will upgrade the package later.

I hope this solves your problem

**Comment by elbrodelche** [comment]
That works like a charm. Thanks!
