### ISSUE TITLE
请问 only 对 relations 有用吗

### ISSUE THREAD

**Issue by JoeShi** [Neil-UWA/loopback-remote-routing#7]
我定义了一个对象叫 `Event`, `Event` referencesMany `user` (relation 的名字叫 `attendees`).

我在

```
  "mixins": {
    "RemoteRouting": {
      "only": [
        "attendees"
      ]
    }
  },
```

结果不起作用？

**Comment by Neil-UWA** [comment]
目前不支持传入relation来关闭relation相关的所有remote methods, 只能是明确指定所要关闭的方法，我有空的时候会把这个支持加上的
